project '25.2.6CocoaPods.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '25.2.6CocoaPods' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 25.2.6CocoaPods
pod 'Alamofire','~> 3.4'
pod 'ObjectMapper', '~> 1.3'
end
