project 'SwiftNews.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftNews' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftNews
pod 'Moya'  
pod 'AlamofireObjectMapper', '~> 3.0'
pod 'Kingfisher', '~> 2.4'
pod 'SnapKit', '~> 0.15.0'
end
